- .asf.yaml
- .gitattributes
- .github/ISSUE_TEMPLATE/iceberg_bug_report.yml
- .github/ISSUE_TEMPLATE/iceberg_improvement.yml
- .github/ISSUE_TEMPLATE/iceberg_question.yml
- .github/dependabot.yml
- .github/labeler.yml
- .github/workflows/go-ci.yml
- .github/workflows/labeler.yml
- .github/workflows/license_check.yml
- .gitignore
- .pre-commit-config.yaml
- LICENSE
- NOTICE
- README.md
- dev/.rat-excludes
- dev/check-license
- errors.go
- go.mod
- go.sum
- schema.go
- schema_test.go
- types.go
- types_test.go
- utils.go
Initial dev setup scripts / github actions configs etc.
Plus initial schema and types implementation
> feat: schema and types

- .gitignore
- dev/.rat-excludes
> Ignore IntelliJ files

- io/s3.go
broken out from #118 to shrink that PR.
Remove the usage of the deprecated S3 APIs
> chore(s3): update to remove deprecated s3 sdk

- literals.go
- manifest.go
- transforms.go
- types.go
Some more small refactor changes being split out of #118 to shrink the scope of that PR. 
This should be the last one I believe, the PR should be hopefully small enough to review after this.
> refactor: some more small refactors

- dev/release/verify_rc.sh
> `verify_rc.sh`, download artifacts from apache dist

- catalog/registry.go
- catalog/registry_test.go
Hi team,
I'm new to iceberg and iceberg-go and working on the adoption at my current company. I was digging at the code and found some area to contribute to. Not saying achiving 100% code coverage is always good but it serves as an entry point for my understanding of the intenals :bow:
> ci(catalog): Improvement to unittest cases in catalog/registry.go

- README.md
- catalog/rest/rest.go
- catalog/rest/rest_test.go
Similar to the `CheckNamespaceExists` method, I add a new method called `CheckTableExists` and add some unit tests
> Add CheckTableExists method for rest.go

- catalog/rest/rest_test.go
Add tests for RegisterTable method
> Add test for RegisterTable method

- cmd/iceberg/main.go
closes: #61 
Added based on this https://github.com/docopt/docopt#help-message-format
```
iceberg -h
Usage:
iceberg list [options] [PARENT]
iceberg describe [options] [namespace | table] IDENTIFIER
iceberg (schema | spec | uuid | location) [options] TABLE_ID
iceberg create [options] (namespace | table) IDENTIFIER
iceberg drop [options] (namespace | table) IDENTIFIER
iceberg files [options] TABLE_ID [--history]
iceberg rename [options] <from> <to>
iceberg properties [options] get (namespace | table) IDENTIFIER [PROPNAME]
iceberg properties [options] set (namespace | table) IDENTIFIER PROPNAME VALUE
iceberg properties [options] remove (namespace | table) IDENTIFIER PROPNAME
iceberg -h | --help | --version
Commands:
describe    Describe a namespace or a table.
list        List tables or …
```
> feat(cmd/iceberg): Add commands for iceberg CLI.

- .github/workflows/go-integration.yml
- io/blob.go
- io/io.go
- io/s3_integration_test.go
Fixes #302 and adds integration test for writing to an S3 compatible (minio) FS
> fix(io): fix blobFS writing

- partitions.go
- partitions_test.go
- transforms.go
- transforms_test.go
- types.go
This is necessary for snapshot creation and new datafiles/manifests for writing.
> feat(partitions): Add PartitionToPath method to Specs

- table/locations.go
- table/locations_test.go
- table/properties.go
- table/table.go
Add the location provider interface and simple implementation
> feat(table): Simple location provider

- internal/utils.go
- manifest.go
- manifest_test.go
- table/evaluators_test.go
- table/snapshots.go
- table/snapshots_internal_test.go
Next step to getting writes up and working
> feat(table): Adds updateSnapshotSummary internal function

- catalog/glue/glue.go
- catalog/glue/glue_test.go
Hi team,
I made a dumb mistake in https://github.com/apache/iceberg-go/pull/326 that the table created is a standard AWS Glue Table.It should ,however, be Apache Iceberg-type table instead. I'm really sorry for that :( 
After `CreateTable` method is called, AWS Glue will create a brand new blob to store the metadata file under the format of `${metadataLocation}/metadata/00000-00000-00000-00000-00000.metadata.json`. If user already has an existing metadata file in S3, `RegisterTable` method should be used instead, similar to `RegisterTable` in REST catalog https://github.com/apache/iceberg-go/blob/9572985db3913f2a9c5c711e5a40cd61769c21aa/catalog/rest/rest.go#L806-L830
Also, let me know if we want to drop `TestGlueCreateTableSuccessIntegration` for now because I think it is quite …
> feat: (catalog/glue): Fix glue table type

- catalog/sql/sql.go
- io/s3_integration_test.go
> fix(catalog): strip trailing slash for warehouse paths

- table/metadata.go
- table/metadata_internal_test.go
> fix(table): remove inconsistencies in metadata serialize

- catalog/rest/options.go
- catalog/rest/rest.go
- catalog/rest/rest_integration_test.go
Includes a few fixes that were found when writing the test
> fix(catalog): add rest integration write test

- table/metadata.go
- table/metadata_internal_test.go
- table/updates.go
`addPartitionSpecAction` should be `add-spec` and not `add-partition-spec`.
> fix(table): for add partition spec constant

- table/table.go
- table/table_test.go
> fix(table): logging error when deleting old metadata

- table/internal/utils.go
- table/internal/utils_test.go
While trying to to use `table.Transaction.AddFiles` API, I was getting this error, which was odd since I have a day transform. Digging into the code I found that we were comparing without applying the transform.
```
failed to add file to transaction: error encountered during parquet file conversion: cannot infer partition value from parquet metadata as there is more than one value for partition field: date_partition. (low: 1733183899000000, high: 1733183942000000)
```
This PR ensures that we first apply the transform and then do the comparison.
Ref: https://apache-iceberg.slack.com/archives/C05J3MJ42BD/p1747319038338949
> fix(table): apply transform before comparing lower and upper partition values

- internal/recipe/docker-compose.yml
- io/gcs.go
- io/gcs_integration_test.go
Otherwise we aren't able to access private blobs with credentials.
If no credentials are found, fall back to the anonymous http client.
> Use gcp.NewHTTPClient and pass creds

- internal/recipe/provision.py
Remove all mentions of `CREATE OR REPLACE` issue, https://github.com/apache/iceberg/issues/8756
Similar to https://github.com/apache/iceberg-python/pull/2137 and https://github.com/apache/iceberg-python/pull/2140
> test: use `create or replace`

- catalog/rest/rest.go
- catalog/rest/rest_internal_test.go
> fix(catalog/rest): pass key-scope

- .asf.yaml
- .github/workflows/go-release-docs.yml
- CONTRIBUTING.md
- website/.gitignore
- website/README.md
- website/book.toml
- website/src/CONTRIBUTING.md
- website/src/SUMMARY.md
- website/src/api.md
- website/src/cli.md
- website/src/glossary.md
- website/src/install.md
- website/src/introduction.md
Part of: https://github.com/apache/iceberg-go/issues/477
> docs: Introduce website with docs

- README.md
- website/src/introduction.md
see: apache/iceberg#9783
related: https://github.com/apache/iceberg-go/issues/477
> docs: remove mentiones of dynamodb
