go.mod, go.sum, table/metadata.go, table/metadata_test.go, table/refs.go, table/refs_test.go, table/snapshots.go, table/snapshots_test.go, table/sorting.go, table/sorting_test.go, table/table.go, table/table_test.go
Basic table/metadata/snapshots implementation
CC @rdblue @nastra @Fokko @coded9 @bitsondatadev
=> feat(tables): add basic table implementation

internal/avro_schemas.go, manifest.go, manifest_test.go
Updating that `added_snapshot_id` is mandatory in both V1 and V2 as per https://github.com/apache/iceberg-go/pull/3#discussion_r1354308095
=> fix(manifests): Make `added_snapshot_id` mandatory in V1

.asf.yaml
In the other Iceberg repositories, the merge commit has been disabled to avoid non-linear history. What are your thoughts on setting this on `iceberg-go` as well to maintain some level of consistency?
=> Disable merge commit

README.md
It will be better to add the build instruction for the newcomers
even though it might be straight for Go develop to find where's main.go file.
By the way, I'm wondering if adding the Makefile to manage the build and test instructions
is good. If yes,  I would submit a PR to resolve this.
=> Add the build from source section

errors.go, exprs.go, literals.go, literals_test.go, partitions.go, schema.go, table/metadata.go, table/metadata_test.go, table/refs.go, table/sorting.go, table/table.go, utils.go, visitors.go, visitors_test.go
This PR implements some basic expression visitors for boolean expressions: including a BindExpr visitor, RewriteNotExpr visitor, ExpressionEvaluator, and a ManifestEvaluator.
Appropriate unit tests are included along with adding `MarshalBinary` and `UnmarshalBinary` methods for Literals in order to process partition field statistics.
=> feat(visitors): Implement basic boolean expression visitors

io/local.go, manifest.go
Split out from #118 
Fixup the partition data map that we get from the manifest entry's datafile information and preserve the field name -> field-id mapping in partition data for a datafile.
=> feat(manifest): fix partition data map

cmd/iceberg/output.go
Empty table does not have "Current Snapshot" causing describe command to be failed.
Added validation to replace with empty string `""`.
Steps to reproduce
1. Start env `docker-compose -f dev/docker-compose.yml up -d`
2. Create namespace
```
curl --location --request POST 'localhost:8181/v1/namespaces/public/tables' \
--header 'Content-Type: application/json' \
--data-raw '{
"schema": {
"type":"struct",
"fields": [
{
"id":1,
"name": "col1",
"type": "boolean",
"required": true
}
]
},
"name": "t"
}
'
```
3. Describe table `t`: `iceberg describe public.t --uri=http://localhost:8181`
Actual result
```
Table format version | 2
Metadata location    | s3://warehouse/public/t/metadata/00000-c2e47505-8693-4254-b335-437111d400f0.metadata.json
Table UUID           | …
```
=> fix: SIGSEGV when describe empty table

cmd/iceberg/output_test.go, go.mod
@zeroshade 
1. I've figured out how to run tests with pterm, but there are a few questions I need your input on.
```
var buf bytes.Buffer
pterm.SetDefaultOutput(&buf)
text{}.DescribeTable(table)
// compare buf.String() with expected result
```
or
```
pterm.SetDefaultOutput(os.Stdout)
text{}.DescribeTable(table)
// Output:
// Expected output
```
2. Also we need to disable colors. Otherwise output has ANSI codes, making comparison impossible.
```
pterm.DisableColor()
```
3. Not sure if we can reuse `Examples`.
https://github.com/golang/go/issues/26460
```
The trailing spaces cannot be handled by the // Output: of an Example
```
In our case, `Metadata location    | ` has whitespace after the pipe `|`, which is getting removed.
```
// Output:
// Table format version | 2
// Metadata location …
```
=> Test: Add coverage for Output

catalog/glue.go, catalog/glue_test.go
Add support for `ListNamespaces` to the Glue catalog.
- Similar to tables, used the same `ICEBERG` parameter to differentiate between Iceberg catalog databases and other databases in the Glue catalog.
- Throw an error when `parent` parameter is given to `ListNamespaces` to align with [Python](https://github.com/apache/iceberg-python/blob/main/pyiceberg/catalog/glue.py#L709C11-L709C50) implementation.
- Tests are added similar to others in the test file.
- Set up AWS Glue Catalog in my personal account and created a database and verified that it can be fetched.
=> feat(catalog/glue): add support for list namespaces

cmd/iceberg/main.go, config/config.go, config/config_test.go, go.mod
Handle config file `.iceberg-go.yaml` in the home directory.
Closes #62 
@zeroshade I noticed that `--catalog` has different functionality compare to pyiceberg cli, where it defines catalog name to be loaded from configuration file.
iceberg-go - `--catalog` - catalog type.
pyiceberg `--catalog` - catalog name to load from configuration file.
Because of this reason, currently it can load only `default` catalog.
Another note is that `docopt` throw's exception when struct has some non default values.
https://github.com/docopt/docopt.go/issues/55
Because of this limitation, I can't first parse configuration file and then provide the same struct to `docopt` to ensure the correct precedence. instead I added this manual mapping:
```
func mergeConf(fileConf *config.CatalogConfig, resConfig …
```
=> Config File Handling

manifest.go
I think the summary line is self-explanatory. There seems to be a typo in the `*dataFile.EqualityFieldIDs()` method that results in stack overflow.
=> Fix infinite recursion bug in EqualityFieldIDs accessor

cmd/iceberg/main.go
Fix iceberg cli when running commands with `--catalog glue` option.
=> cmd/iceberg: Pass default aws config to glue catalog constructor

dev/release/README.md, dev/release/verify_rc.sh
Deprecate the use of 
- https://dist.apache.org/repos/dist/dev/iceberg/KEYS
in favor of 
- https://downloads.apache.org/iceberg/KEYS which is an alias for https://dist.apache.org/repos/dist/release/iceberg/KEYS
devlist discussion: https://lists.apache.org/thread/8j41w4y2jx6r3ybj0o82bfyn0npmhgx2
=> use `dist/release` KEYS

manifest.go, manifest_test.go, utils.go
#172 
This PR adds Builders for v1/2 ManifestEntry and for DataFile as well as helper funcs to write ManifestLists and Manifest files.
Bonus: fixes a max recursion depth panic in `dataFile.EqualityFieldIDs()`
One thing I'm not super happy with is `manifestEntryV1/2.Data`'s type has been changed from `dataFile` to `DataFile` (the interface type). This was the best way I could come up with to make the builders for both work, but I also feel like it diverges from the pattern a little bit. This may not be a huge deal, but something to consider. You can see how the effects rippled out a little bit in the tests.
=> feat: more builders and writing manifests

table/arrow_scanner.go, table/scanner.go, table/table.go
This PR introduces an option to set `MaxConcurrency` for the `Scanner`, allowing users to control the level of concurrent downloads in Scanner. This configuration can be beneficial for workloads running multiple simultaneous queries.
Additionally, this PR changes the default value of max concurrency from `runtime.NumCPU()` to `runtime.GOMAXPROCS`. While both are initially set to the number of available CPUs, `GOMAXPROCS` is adjustable by users, providing greater flexibility. This change addresses a limitation of using `runtime.NumCPU()`, which does not account for cgroup limits. For instance, in Kubernetes environments, using `runtime.NumCPU()` may incorrectly assume access to all CPU cores on a node, rather than only the cores allocated to the specific pod. This mismatch can lead to …
=> Add option to set max concurrency for table scan operations

.github/workflows/rc.yml
Follow up to #199.
For the RC workflow running on a tag, there was an issue resulting in the wrong filename used for the `tar.gz` file, for example, `apache-iceberg-go-0.1.0-rc1-rc1.tar.gz`. Notice the extra `-rc`. 
This is due to the parsing logic which is fixed in this PR.
For details, see https://github.com/apache/iceberg-go/actions/runs/11821595808/job/32936689238
where the `Archive` job's `Archive` step has the following
```
env:
VERSION: 0.1.0-rc1
RC: 1
```
Tested in fork repo.
`v0.1.0-rc1` release https://github.com/kevinjqliu/iceberg-go/releases/tag/v0.1.0-rc1
https://github.com/kevinjqliu/iceberg-go/actions/runs/11824564368/job/32946341965
Downloaded artifacts in https://github.com/kevinjqliu/iceberg-go/actions/runs/11824501122 and checked the sha256 file is correct
=> Fix `version` and `rc` in `rc.yml`

dev/release/release.sh
This takes the artifacts from the dev `svn` and copies them to the release svn.
=> Use `svn mv` instead for releasing

dev/docker-compose.yml
Updates docker compose file in `dev` to use `apache/iceberg-rest-fixture`
Closes https://github.com/apache/iceberg-go/issues/221
=> Update `tabulario/iceberg-rest` to `apache/iceberg-rest-fixture`

dev/release/release_rc.sh
#204
While running `release_rc.sh` for RC2, I noticed that the .asc file was not generated. 
There's a bug in the script similar to #199 and #202 where the filename does not include the RC version. 
This PR fixes the script to use the correct file name, `apache-iceberg-go-0.1.0-rc2.tar.gz`, which corresponds with the artifacts here https://github.com/apache/iceberg-go/releases/tag/v0.1.0-rc2
Tested in terminal
```
version=0.1.0                            
rc=2
id="apache-iceberg-go-${version}-rc${rc}" 
tar_gz="${id}.tar.gz"
echo $tar_gz
> apache-iceberg-go-0.1.0-rc2.tar.gz
```
=> Fix `release_rc.sh`, use the right artifact file name 

.github/workflows/rc.yml, dev/release/README.md, dev/release/verify_rc.sh
Sha512 is enough, Sha256 is not necessary
devlist: https://lists.apache.org/thread/rsl3rj9rcqvchb8dqr8tjky97rt5pm22
Part of #204
=> ci(infra): Remove sha256

catalog/catalog.go, catalog/glue.go, catalog/registry.go, catalog/registry_test.go, catalog/rest.go, catalog/rest_test.go
Allow flexibility for handling catalogs and catalog implementations by adding a Catalog Registry to make it easy to add custom catalog implementations.
The Registry allows registering an identifier mapped to a factory function, with the URI scheme being used if provided or otherwise to create a catalog on the fly.
=> feat(catalog): Add Catalog Registry

table/scanner.go
This refactor breaks down the manifest scanning logic into more focused components in preparation for adding incremental scanners to allow reading changelog and diffs between two snapshots.
Key changes include:
- Add manifestEntries type to safely collect data and delete entries concurrently
- Split manifest handling into separate fetchPartitionSpecFilteredManifests and collectManifestEntries functions for better separation of concerns
- Replace manual goroutine management with errgroup for more robust concurrency
- Add documentation comments explaining the manifest scanning process
This is a step toward adding a [ManifestGroup](https://github.com/apache/iceberg/blob/main/core/src/main/java/org/apache/iceberg/ManifestGroup.java) abstraction similar to the Java implementation that can be …
=> refactor: improve manifest scanning organization and concurrency

catalog/catalog.go, catalog/glue.go, catalog/rest.go, partitions.go, schema.go, schema_test.go, table/metadata.go, table/metadata_internal_test.go, table/sorting.go
Adding a CreateTable function to the `Catalog` interface, standardizing the implementation that was initially created by #146 so that it isn't specific to the REST catalog and can be implemented by any catalog.
This also requires adding the `AssignFresh*IDs` functions so that the REST catalog implementation is correctly re-assigning IDs as other implementations do.
=> feat(catalog): Standardize Catalog create table function

catalog/registry.go, catalog/registry_test.go, catalog/rest.go, catalog/rest_test.go, cmd/iceberg/main.go, config/config.go, config/config_test.go
As brought up in https://github.com/apache/iceberg-go/pull/244#discussion_r1911257805 this PR implements using a "type" property when loading catalogs and looking up catalog configurations using the provided "name", only using the uri scheme as a fallback when necessary.
=> feat(catalog): Have Load use "type" property and "name" for config

catalog/catalog.go, catalog/glue.go, catalog/rest.go
Continuing the march towards better catalog support and shrinking the size of the SQL Catalog PR, this smaller PR just includes adding a `CommitTable` method to the `Catalog` interface and implements it for the REST catalog.
=> feat(catalog): Add CommitTable method

internal/mock_fs.go, io/blob.go, io/io.go, io/local.go
Again, continuing the march towards better Catalog support, the SQL catalog needs to be able to write files (and we'll eventually need it for manifest and table updates) so this adds a `Create` method to the `WriteFileIO` interface and implements it for our supported file systems so that we can create a file and get a writer for it.
=> feat(io): Add Create method for creating file writers

catalog/catalog.go, catalog/rest.go, catalog/rest_test.go
fixes https://github.com/apache/iceberg-go/issues/263
As part of debugging the test update I noticed that multiple http clients are created each time a rest client is created
=> feat(catalog): Make rest catalog auth scope configurable

catalog/rest.go
This change shouldn't really be necessary..... but I just spent the better part of an afternoon tracking it down. 
I've been testing against snowflake opencatalog and it appears that they're running some older version of `polaris` where a bug exists where if you specify a `Content-Type` header multiple times on a `POST` you'll get a cryptic 400 back from the server. I wasn't able to find a bug in `apache/polaris`, but the problem doesn't happen on main. 
Seems safe to do as the header is [defaulted here.](https://github.com/apache/iceberg-go/blob/main/catalog/rest.go#L555)
```
iceberg-go/rgc % curl -X GET -H "Authorization: Bearer xxx" \ 
-H 'Accept: application/json' \
-H 'Accept: application/json' \
-H 'Content-Type: application/json' \
-H 'Content-Type: application/json' \ …
```
=> Do not set Content-type header in doPost

catalog/catalog.go, catalog/glue/glue.go, catalog/glue/glue_test.go, catalog/glue/options.go, catalog/internal/utils.go, catalog/registry_test.go, catalog/rest/options.go, catalog/rest/rest.go, catalog/rest/rest_internal_test.go, catalog/rest/rest_test.go, cmd/iceberg/main.go, table/scanner_test.go
Refactoring and restructuring the `catalog` package based on discussions with others in the Go community. This achieves the following benefits:
* Improved, and shorter, naming of types and methods. Things that are specific to the REST catalog or Glue catalog can be put directly into those packages allowing for a public API such as `rest.NewCatalog` instead of `catalog.NewRestCatalog`. Options can be made specific to catalog implementations without weird generic handling, etc.
* Using the Registry allows consumers to only import the catalog implementations they care about, allowing any others to be pruned and removed by the compiler as unused and unreachable if not imported. This will enable smaller binaries if not all catalog implementations are needed.
=> refactor(catalog): restructure catalog package

catalog/glue/glue.go, catalog/internal/utils.go, catalog/registry.go, catalog/registry_test.go, catalog/rest/rest.go, catalog/rest/rest_internal_test.go, catalog/rest/rest_test.go, catalog/sql/sql.go, catalog/sql/sql_test.go, cmd/iceberg/main.go, io/blob.go, io/io.go, io/s3.go, table/arrow_scanner.go, table/arrow_utils.go, table/arrow_utils_test.go, table/scanner_test.go
In general we should pass `context.Context` through call path rather than creating `context.Background` at random places.
I made this change in response to [this comment](https://github.com/apache/iceberg-go/pull/275#issuecomment-2617075856). I'll fix the original problem in a subsequent PR.
=> feat(catalog): Propagate ctx from catalog interface through call stack

.github/dependabot.yml
The intent of this PR is to configure dependabot to bundle these dependency upgrades together in one PR instead of one PR per dependency bump.
It looks like #281, #282, #283, #284, and #285 are individual dependabot PRs that are causing some headaches for you, as related dependencies are trying to be bumped out of step.  #288 manually bundles some together and yields a working CI pipeline.
Maybe this proves useful to you, the documentation for it is [here](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#groups--)
=> chore: tweak dependabot to bundle all go mod upgrades into the same PR

catalog/glue/glue.go, io/s3.go, utils/context.go
Store `aws.Config` in glue catalog so we don't need to pass config to `catalog.LoadTable(...`
=> feat(catalog/glue): Use awscfg from catalog creation when loading data from glue

README.md, catalog/catalog.go, catalog/rest/rest.go, catalog/rest/rest_test.go
From the [REST catalog API](https://raw.githubusercontent.com/apache/iceberg/refs/heads/main/open-api/rest-catalog-open-api.yaml), we can support a few more operation related to views
=> feat(catalog/rest): Add support for view related operations

README.md
Added description of CLI usage in README similar to pyiceberg.
https://py.iceberg.apache.org/cli/
=> docs(cmd/iceberg): Added description of CLI usage in README

catalog/catalog.go, catalog/glue/glue.go, catalog/glue/glue_test.go, catalog/rest/rest.go, catalog/rest/rest_test.go, catalog/sql/sql.go, catalog/sql/sql_test.go, cmd/iceberg/main.go
To support pagination for ListTables method. Similar to `ListViews` operation in PR https://github.com/apache/iceberg-go/pull/290. We need to change the method interface in `catalog.go` , cascading changes into `glue.go` and `sql.go`. I'm not sure about the pagination in `sql.go` so I write a wrapper to convert the existing function to iter.Seq2[] type
=> feat(catalog): Add pagination for list table operation across different catalog types

README.md, catalog/glue/glue.go, catalog/glue/glue_test.go
Hi team,
Its a smaller PR this time round. I did a check in the https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/glue but couldnt find any method to directly check namespace's existance. Hence, I borrow similar logic from `DropNamespace` where we also check if a namespace exists before deleting it
=> feat(catalog/glue): add checkNamespaceExist

.github/workflows/go-integration.yml, catalog/rest/rest.go, catalog/rest/rest_integration_test.go
Brought up by #291 we need to add some simple integration tests for the REST catalog to ensure that our requests and handling are correct according to the spec and not just according to our mocked request/responses.
This creates an initial framework for adding REST integration tests (more need to be added) which already discovered an issue in the delete requests that is also fixed by this PR.
=> ci(catalog/rest): initial framework for rest catalog integration tests

catalog/catalog.go, internal/utils.go, internal/utils_test.go, utils.go
Let's not expose this helper function, keep it as an internal util so we don't have it as part of the public API
=> refactor: move Difference to internal

exprs.go, internal/utils.go, name_mapping.go, name_mapping_test.go, schema.go, table/arrow_scanner.go, table/arrow_utils.go, table/arrow_utils_internal_test.go, table/arrow_utils_test.go, table/internal/interfaces.go, table/internal/parquet_files.go, table/metadata.go, table/metadata_internal_test.go, table/properties.go, table/snapshots.go, table/snapshots_internal_test.go
This one's a big one!
Adding initial implementation of deriving and computing the Iceberg metadata statistics from Parquet files in order to facilitate adding files directly. This includes utilizing the Parquet file metadata retrieve the typed statistics and collecting them based on optional metrics modes and so on. This also includes various unit tests to confirm it is working.
=> feat(table): Add computation of iceberg stats from parquet files

catalog/glue/glue.go, catalog/glue/glue_test.go, catalog/glue/schema.go, catalog/glue/schema_test.go
Hi team,
This PR aims to support CreateTable for glue catalog. Below are the list (I think) to be done:
=> feat: (catalog/glue) Add support for CreateTable

manifest.go, manifest_test.go, table/evaluators_test.go
Following up on #327, simplifying some code by consolidating the ManifestFileV1/V2 objects into a single object and interface covering it while ensuring we read/write correctly based on the underlying version of the table.
=> feat(manifests): Consolidate V1/V2 manifest file objects

README.md
The `tabulario` images are not maintained anymore.
=> Replace `tabulario` in favor of `apache`

manifest.go, manifest_test.go
Hi,
I'm working on [a tool that leverage this package](https://github.com/agnosticeng/icepq) to support adding / removing / merging Parquet files from ClickHouse with an UDF.  
After upgrading this package (and removing a lot of code thx to your last commits) I got errors from ClickHouse (again) at query time.
I nailed the issue down to the "partition-spec" metadata of the manifest file.
When there is no field in the partition spec, the current code write a "null" JSON document that cause errors with ClickHouse.
I just replaced "null" with "[]" in this case and things are working ok again.
Fixes #344
=> fix: Clickhouse does not support "null" as partition spec metadata

table/table.go, table/table_test.go
fixes #346 
Was using the wrong path when generating the Metadata in the tests `createTable` method.
=> fix(table): fix funky test paths

README.md, catalog/glue/glue.go, catalog/glue/glue_test.go
Hi team,
Im adding RegisterTable implementation for Glue catalog to match what we currently have in py-iceberg and REST catalog
https://github.com/apache/iceberg-python/blob/83cc1783e20edf8998c20fed47b5f126481db4db/pyiceberg/catalog/glue.py#L443-L463
=>  feat: (catalog/glue): Add RegisterTable method in Glue catalog

catalog/glue/glue.go
database name is missing from loaded table. Subsequent load or refresh of table is not possible.
Use identifier passed to LoadTable while after creating iceberg table.
=> fix(glue): create new table with database and table name on LoadTable

go.mod, go.sum, table/scanner_test.go
closes #335 
Bump the arrow-go version to incorporate the new IsIn compute functionality for filtering Arrow record batches and tables. Also adding a unit test to confirm that the IsIn row filter works now.
=> fix(table): make IsIn filter work

catalog/rest/rest_integration_test.go
Don't know how this slipped past but it looks like the integration test has a bad merge or something causing a build failure
=> fix(catalog/rest): fix build

catalog/rest/rest_integration_test.go, config/config.go, table/internal/utils.go, table/snapshot_producers.go, table/snapshots.go, table/snapshots_internal_test.go, table/table_test.go, table/transaction.go
Implementing a simple `ReplaceDataFiles` method for transactions to create an `Overwrite` operation for deleting/adding files in a single operation for use with compaction operations or otherwise replacing one or more data files with new data files.
=> feat(table): add ReplaceFiles method to transaction

.asf.yaml
This will prevent merge conflicts, such as #364 
We added it to pyiceberg, https://github.com/apache/iceberg-python/pull/1640
=> Repo: Set status checks to strict

.github/workflows/go-ci.yml, .golangci.bck.yml
Upgrade golangci-lint so Apache INFRA stops blocking it
Migrated config to v2 of golangci-lint.
=> ci: fixing the golangci action

README.md, catalog/catalog.go, catalog/rest/rest.go, catalog/rest/rest_test.go
Currently, I'm returning only the error instead of a iceberg view class instance. The reason is because the response return in `metadata` key is quite different from the table related operation and will require some significant work to refactor https://github.com/apache/iceberg-go/blob/main/table/metadata.go. Let me know if you want to pursue that direction :pray:
=> feat (catalog/rest): Add create view for rest catalog

table/internal/utils.go, table/internal/utils_test.go
If pushing to chan ch is not done in a goroutine, we never reach the point where we return the iterator func to the caller.
=> fix(table): a bug in MapExec that triggers when len(slice) > nWorkers.

table/requirement_test.go, table/requirements.go
Added `ParseRequirement` and its string and bytes counterpart to facilitate parsing the Requirement interface based on type.
Part of #381
=> feat(table): Add json parsing of table Requirement

table/metadata.go, table/updates.go
Moved all action names in table updates to constants.
As a first step before implementing parsing of updates from bytes as described in #381
=> refactor(table): move all action names to constants

catalog/rest/options.go, catalog/rest/rest.go, catalog/rest/rest_internal_test.go
A hasher is not thread-safe, yet the same hasher was being used for all requests. If applications made concurrent calls to the same REST catalog implementation, they could end up writing to the same hasher, corrupting the signatures for both concurrent requests.
This makes things thread-safe by creating a hasher for each signing operation. The could be safely re-used using a `sync.Pool`. But the hasher is only 116 bytes, and initialization just has to write 8 bytes (other than the zero'ing done by the allocator), so it doesn't seem worth trying to re-use them.
=> fix(catalog/rest): Fix concurrency bug in REST catalog request signing

manifest.go, manifest_test.go
The schemas in Avro manifest and manifest list files should be self-contain and not contain references to types that aren't defined in the OCF's schema metadata.
But, by default, encoders and decoders in Avro's `ocf` package use a global default schema cache, and can resolve named types using that cache.
This change avoids using the global default schema cache by effectively not using a cache at all. There's not an actul way to disable use of a schema cache, so the next best thing is to create a new, empty schema cache for each operation. This ensures when reading manifests and manifest lists that their schemas are self-contained (i.e. no named types can be inadvertently resolved via cache populated from some other package or OCF file) and also makes sure that schemas used to generate …
=> fix(manifests): Don't use avro.DefaultSchemaCache

manifest.go, manifest_test.go
This is a follow-up to #385, which added a similar test for manifest _lists_ (but not for manifest files).
I verified the efficacy of this new test by commenting out the calls to `ocf.WithDecoderSchemaCache` in `readManifestEntries` and `NewManifestWriter` (which were added in #385). When they are commented out, the process uses avro's default global cache and the test then fails (as expected) with the following:
```
=== RUN   TestManifests/TestReadManifestIncompleteSchema
manifest_test.go:911: 
Error Trace:	/Users/jhumphries/src/iceberg-go/manifest_test.go:911
Error:      	An error is expected but got nil.
Test:       	TestManifests/TestReadManifestIncompleteSchema
--- FAIL: TestManifests/TestReadManifestIncompleteSchema (0.00s)
```
=> Add test to verify that no avro schema cache is used with manifest files

catalog/glue/glue_test.go
* Fix glue integration test failures. Mostly caused by asserting table identifiers, which require both database name and table name.
* Ran the integ tests locally with AWS environment variables set
=> fix(catalog/glue): Fix glue integration test failures

catalog/catalog.go, catalog/glue/glue.go, catalog/glue/glue_test.go, catalog/sql/sql.go, cmd/iceberg/main.go
* Implement `CommitTable` defined in the catalog interface
* It will takes in `updates` and apply them on the base table and create a staging table
* The table transaction will create a new metadata in the metadata location with the updated metadata / schema
* The new metadata file will be committed to Glue catalog
@maninc is on leave, so I'm adding his previous work in https://github.com/apache/iceberg-go/pull/378 to this PR as well.
Added `TestAlterTableIntegration` and tested locally
=> feat: Add commit table support for Glue Catalog

catalog/catalog.go, catalog/glue/glue.go, catalog/glue/schema.go, catalog/glue/schema_test.go, catalog/internal/utils.go, catalog/sql/sql.go
fixes #407
Update and improve the Glue catalog CreateTable to properly set the parameters on the table itself and the columns (such as iceberg.field.id and iceberg.field.optional).
Also, write out the metadata first and then pass the location to Glue as part of creating the table.
=> fix(catalog/glue): create table with required fields

manifest.go, manifest_test.go
This is an alternative to #415.
This closes #386.
This also exports the `ReadManifest` helper (previously named `readManifestEntries`), so the read flow has symmetry with the existing `NewManifestWriter` and `WriteManifest` for the write flow.
=> Add ManifestReader, which provides access to manifest metadata

catalog/rest/rest.go
This one-liner uses the "net/http" package's built-in support for HTTP proxies, activated via standard environment variables like `HTTP_PROXY`, `HTTPS_PROXY`, and `NO_PROXY`.
=> Allow HTTP proxy to be used to talk to REST catalog server

cmd/iceberg/main.go
* This make sure that catalog doesn't support hierarchical namespaces will be able to run the list tables correctly.
* This change also aligned with the current behavior in iceberg-python https://github.com/apache/iceberg-python/blob/main/pyiceberg/cli/console.py#L114-L121
```
go run . list --catalog glue                         
┌────────────────────┐
| IDs                |
| ------------------ |
| lliangyu_test_db   |
| lliangyu_test_db_2 |
└────────────────────┘
go run . list lliangyu_test_db_2 --catalog glue
┌─────────────────────────┐
| IDs                     |
| ----------------------- |
| lliangyu_test_db_2.tb1  |
| lliangyu_test_db_2.tb2  |
| lliangyu_test_db_2.tb3  |
| lliangyu_test_db_2.tbl4 |
| lliangyu_test_db_2.tbl5 |
| lliangyu_test_db_2.tbl6 |
| lliangyu_test_db_2.tbl7 |
| …
```
=> fix: Improve list logic to fallback from tables to namespaces

cmd/iceberg/main.go, schema.go, schema_test.go
* Adds support for creating table through CLI
* The schema needs to be provided in json form
* An alternative idea is to use SQL like form like `id bigint NOT NULL COMMENT 'unique id'`, but the parsing may get complicated with nestings.
```
go run . create table lliangyu_test_db.test_tbl \                         
--catalog glue \
--schema '[{"name":"id","type":"int","required":false},{"name":"name","type":"string","required":true}]' \
--location-uri s3://xxxxx/xxxxx
```
Result metadata file
```
{"last-sequence-number":0,"format-version":2,"table-uuid":"bc6fd1b7-6855-428b-a5f3-65b8fa742e84","location":"s3://xxxxx/xxxxx","last-updated-ms":1746826023185,"last-column-id":2,"schemas":[{"type":"struct","fields":[{"type":"int","id":1,"name":"id","required":false},{"type":"string","id":2,"name":" …
```
=> feat: Add initial support for create table CLI through json schema

catalog/glue/glue.go
When calling NewCatalog in glue catalog without any AWS properties, causing the catalog properties to be nil
```
props:     iceberg.Properties(glueOps.awsProperties),
```
Hence, when creating a staged table and need to clone the catalog properties in https://github.com/apache/iceberg-go/blob/d51f8b8c5b8249a706467910d42ee51eb6032ccd/catalog/internal/utils.go#L137-L138, it will result in nil map assignment.
Similar is happening in 
```
func prepareProperties(icebergProperties iceberg.Properties, newMetadataLocation string) iceberg.Properties {
glueProperties := maps.Clone(icebergProperties)
```
where if staged table has no properties in the metadata, it will return nil and causing nil map.
Glue integration tests were failing because they are using `NewCatalog(WithAwsConfig(awsCfg))`. Re-ran …
=> fix(catalog/glue): Fix nil map assignment issue in glue catalog

README.md, catalog/glue/glue_test.go
* With commit table implemented in glue catalog https://github.com/apache/iceberg-go/pull/403, snapshot management is supported. 
* Add integration test to verify and showcase the usage
* Update README to reflect the status
* Reuse `cleanupTable` as a private util method 
```
--- PASS: TestSnapshotManagementIntegration (7.10s)
PASS
```
=> testing(catalog/glue): Verify glue catalog snapshot management is supported

catalog/glue/glue.go, catalog/internal/utils.go, catalog/rest/rest.go, catalog/rest/rest_integration_test.go, catalog/sql/sql.go, cmd/iceberg/output.go, io/io.go, table/scanner.go, table/table.go, table/table_test.go, table/transaction.go, table/transaction_test.go
related https://github.com/apache/iceberg-go/issues/437
All I/O operations must respect the context passed to PlanFiles(ctx) and simmilar methods.
To support that, we stop passing pre-constructed I/O objects and instead construct them ad hoc within PlanFiles, using the provided context
=> refactor: pass context into actual IO

manifest.go
panics in library code is a bad practice, if we can - we should prefer value err instead.
there is a plenty of panics, so i remove 2 of them (which is more natural as err values).
for the rest of code - better to fix it adhoc (1by1)
=> refactor: remove panics from manifest

cmd/iceberg/main.go
@zeroshade I discover this when I play around with the CLI.
It is useful when we interact with REST endpoint with Oauth capabilities ( Polaris for example )
=> fix(cli/rest): Add custom scope for rest cli when using with Oauth

transforms.go, transforms_test.go
* While implementing `UpdateSpec`, I noticed that some helper methods for transforms are missing. Both Iceberg Python and Java expose a `canTransform` method in the `Transform` interface to validate if a transform can be applied to a given type. Adding this check would help validate inputs before applying spec updates.
* https://github.com/apache/iceberg-python/blob/main/pyiceberg/transforms.py#L157
* https://github.com/apache/iceberg/blob/main/api/src/main/java/org/apache/iceberg/transforms/Transform.java#L69
Added `TestCanTransform`
=> fix(transforms): Add can transform method to transform interface

catalog/sql/sql_integration_test.go
Hi team,
This PR fixes https://github.com/apache/iceberg-go/issues/442
Will need the PR https://github.com/apache/iceberg-go/pull/414 to be merged first before I can uncomment one of the integration test case
=> feat(catalog/sql): Add integration test for sql catalog

partitions.go, partitions_test.go
* Added method to get default partition field name based on transform type
* This method will be a helper for update spec when the partition field is not given (such as `AddIdentity`) and creates default partition field name
* https://github.com/apache/iceberg-go/pull/467/files#diff-eb806166d1b9d570a36b8506d2b9ada56126a32ca94b1eb12d6de03973e292c2R147
* https://github.com/apache/iceberg-python/blob/main/pyiceberg/partitioning.py#L275-L376
* https://github.com/apache/iceberg-go/pull/467
Added unit tests `TestGetPartitionFieldName `
=> feat(partitions): Add support for get partition field name

catalog/glue/glue.go, catalog/glue/glue_test.go
table_type and database_type key values are now
compared against "ICEBERG" string in case-insensitive way
(similar to how PyIceberg and Java implementations work).
Fixes #479
=> fix(catalog/glue): case insensitive type match

table/updates.go, table/updates_test.go
This adds stubs for two of the still missing table updates, remove schemas & remove specs, after that we're still missing:
- UpdateSetStatistics:
- UpdateRemoveStatistics:
- UpdateAddEncryptionKey:
- UpdateRemoveEncryptionKey:
=> feat(table/updates): add stubs for the remove schemas & remove partition specs table updates

catalog/glue/glue_test.go, schema.go, table/arrow_utils.go, table/metadata.go, table/metadata_internal_test.go, table/snapshot_producers.go, table/updates.go, table/updates_test.go
Aligns us a bit more with the Java & Rust implementations where functionally equivalent schemas don't get added a second time. It also aligns renumbering of schemas to be equivalent to java/rust.
Java source: https://github.com/apache/iceberg/blob/41c0b17a20c522e4df519bcc429f413e6a2855e5/core/src/main/java/org/apache/iceberg/TableMetadata.java#L117-L138
Rust source: https://github.com/apache/iceberg-rust/blob/c4c006939a3cb3bf684a0d10ba0e66cac484befe/crates/iceberg/src/spec/table_metadata_builder.rs#L1068
=> feat: reuse schemas & increment their IDS

utils.go
Hi, currently, `iceberg --version` always outputs `(unknown version)`, as `github.com/apache/iceberg-go` isn't present in `info.Deps`.
To reproduce:
```sh
go build ./cmd/iceberg
./iceberg --version
```
=> fix(cli): Fix version detection for CLI

table/metadata.go
This PR removes the newLastColumnID validation check in the MetadataBuilder.AddSchema method. The previous validation required that the new schema's highest field ID must be greater than or equal to the current lastColumnId, but this constraint was incorrect because when columns are deleted from a schema, the HighestFieldID() can legitimately be smaller than the existing lastColumnId.
=> refactor(metadata): remove newLastColumnID check in AddSchema method

io/blob.go, io/io.go, io/local.go, table/orphan_cleanup.go, table/orphan_cleanup_integration_test.go, table/orphan_cleanup_test.go
Hi team,
I believe the `DeleteOrphanFiles` functionality is a valuable addition toward making iceberg-go more feature-complete. This implementation was drafted with reference to the official [Iceberg Java API specification](https://iceberg.apache.org/javadoc/1.2.0/org/apache/iceberg/actions/DeleteOrphanFiles.html).
The PR also includes corresponding unit and integration tests to ensure reliability. Below is some example usages:
```
// Example usage:
// Dry run to see what would be deleted
result, err := table.DeleteOrphanFiles(ctx,
WithDryRun(true),
WithOlderThan(time.Now().AddDate(0, 0, -7)),
)
// Actually delete orphan files with parallel execution
result, err = table.DeleteOrphanFiles(ctx,
WithOlderThan(time.Now().AddDate(0, 0, -3)),
WithMaxConcurrency(8),
)
// Advanced usage with …
```
=> feat(table): Add cleanup orphan files features

catalog/catalog.go, catalog/rest/rest.go, partitions.go, table/arrow_utils_internal_test.go, table/internal/parquet_files_test.go, table/metadata.go, table/metadata_builder_internal_test.go, table/metadata_internal_test.go, table/orphan_cleanup_integration_test.go, table/testdata/TableMetadataV1PartitionSpecsWithoutDefaultId.json, table/testdata/TableMetadataV2MissingLastPartitionId.json, table/testdata/TableMetadataV2MissingPartitionSpecs.json, table/transaction_test.go, table/update_spec.go, table/update_spec_test.go, table/updates.go, table/updates_test.go
This PR:
1. adds a funct-opts builder for PartitionSpec
2. implements the remove PartitionSpec Update
3. ports test relating to PartitionSpecs from iceberg-rust
4. port missing validations from iceberg-rust to metadataBuilder
It's mostly contained within partitions, there's a more fundamental change to json deserialization in there which initializes the deserialization target with `-1` in all int fields so that we are able to determine if we received / did not receive a certain field and are consequently able to reject requests where mandatory IDs are missing.
There's currently still some duplication between the funct-opts constructor of `PartitionSpec` and `update_spec.go`. I'm still working on that one, I hope to arrive at something close to [java's apply() of …
=> feat(metadata): PartitionSpec builder & validations

catalog/glue/schema_test.go, io/azure_integration_test.go, table/arrow_utils_internal_test.go, table/metadata.go, table/metadata_builder_internal_test.go, table/metadata_internal_test.go, table/time_travel_test.go, table/updates.go
This removes the `MetadataBuilder` return value from the mutators of `MetadataBuilder`. Since all those functions are fallible, we cannot use it as a builder anyways. Removing them makes the API more concise and simpler.
=> chore(metadata): remove Builder returns from MetadataBuilder

table/metadata.go, table/metadata_internal_test.go, table/statistics.go
This PR adds support for reading Iceberg table metadata containing statistics and partition statistics fields, as specified in https://iceberg.apache.org/spec/#table-statistics.
=> feat(metadata): Add support for Statistics and PartitionStatistics in table metadata

catalog/glue/schema_test.go, catalog/internal/utils.go, errors.go, table/arrow_utils_internal_test.go, table/metadata.go, table/metadata_builder_internal_test.go, table/metadata_internal_test.go, table/partitioned_fanout_writer_test.go, table/table.go, table/table_test.go, table/time_travel_test.go
- exports UpdateTable so that outside packages can use it
- adds metadata log maintenance to the builder, i.e. based on currentFileLocation, an entry is added to the metadata log & on Build, we trim the metadata log
- ports remaining tests from iceberg-rust and implements fixes for them
=> feat(metadata): export UpdateTable & fixes

.github/workflows/audit-and-verify.yml, .github/workflows/rc.yml, dev/release/verify_rc.sh
Closes #587
Fixes RC artifact. It now produces this structure
```
https://dist.apache.org/repos/dist/dev/iceberg/apache-iceberg-go-0.4.0-rc0/
apache-iceberg-go-0.4.0.tar.gz
apache-iceberg-go-0.4.0 (untar)
```
Additionally, the github release page should have artifacts with 
```
apache-iceberg-go-0.4.0-rc0.tar.gz
apache-iceberg-go-0.4.0-rc0.tar.gz.asc
apache-iceberg-go-0.4.0-rc0.tar.gz.sha512
```
https://github.com/apache/iceberg-go/compare/main...kevinjqliu:iceberg-go:main
`dev/release/release_rc.sh 0.4.0 7`
Release tag: https://github.com/kevinjqliu/iceberg-go/releases/tag/v0.4.0-rc7
rc.yml: https://github.com/kevinjqliu/iceberg-go/actions/runs/18294724035
audit-and-verify.yml: https://github.com/kevinjqliu/iceberg-go/actions/runs/18294715754
Log:
```
➜  iceberg-go git:(main) …
```
=> infra: fix rc artifact structure
